[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Speykious <speykious@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
nom = { version = "6.0.1", feature = "alloc" }